DROP DATABASE IF EXISTS estore;

CREATE DATABASE estore COLLATE 'utf8_general_ci';

USE estore;

CREATE TABLE products (
	id INT(10) NOT NULL AUTO_INCREMENT,
	name VARCHAR(200) UNIQUE,
	price VARCHAR(200) UNIQUE,
	sale_start DATETIME NULL DEFAULT NULL,
	sale_end DATETIME NULL DEFAULT NULL,
	sale_price VARCHAR(200) DEFAULT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE history (
	id INT(10) NOT NULL AUTO_INCREMENT,
	product_id INT(10) NOT NULL,
	language_id INT(10) NOT NULL,
	price FLOAT(2) NOT NULL,
	sale  INT(1) NOT NULL,
	date DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE languages (
	id INT(10) NOT NULL AUTO_INCREMENT,
	code VARCHAR(2) NOT NULL,
	currency VARCHAR(10) NOT NULL,
	decimals VARCHAR(1) NOT NULL,
	thousands VARCHAR(1) NOT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE tr_varchar (
	id INT(10) NOT NULL AUTO_INCREMENT,
	language_id INT(10) NOT NULL,
	code VARCHAR(200) NOT NULL,
	value VARCHAR(200) NOT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE tr_float (
	id INT(10) NOT NULL AUTO_INCREMENT,
	language_id INT(10) NOT NULL,
	code VARCHAR(200) NOT NULL,
	value FLOAT NULL NOT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
